### ISSUE TITLE
Question about AutoDock Vina version supported

### ISSUE THREAD

**Issue by vincrichard** [DeltaGroupNJUPT/Vina-GPU-2.1#2]
Dear authors, thank you for your work.

I have been using Vina GPU with AutoDock Vina v.1.2.5. However, it seems that some of the functionalities in v.1.2.5 is not present in Vina GPU.
Especially on some atom types, which are specific for macrocycle sampling, I get the following error:

```
/opt/elix/vina/Vina-GPU --receptor /nasa/shared_homes/vincent/sandbox/data/DUD-E/parp1/target.pdbqt --ligand /tmp/tmp6sun2q7j/0ofm24e9a.pdbqt --seed 42 --out /tmp/tmp6sun2q7j/0r9uxxf3e.pdbqt --center_x 26.835 --center_y 11.332 --center_z 27.744 --size_x 30.0 --size_y 30.0 --size_z 30.0 --num_modes 1 --thread 8000
#################################################################
# If you used Vina-GPU in your work, please cite:               #
#                                                               #
#Shidi, Tang, Chen Ruiqi, Lin Mengru, Lin Qingde,               #
#Zhu Yanxiang, Wu Jiansheng, Hu Haifeng, and Ling Ming.         #
#Accelerating AutoDock VINA with GPUs. ChemRxiv (2021).Print.   #
#                                                               #
#DOI 10.26434/chemrxiv-2021-3qvn2-v3                            #
#                                                               #
# And also the origin AutoDock Vina paper:                      #
# O. Trott, A. J. Olson,                                        #
# AutoDock Vina: improving the speed and accuracy of docking    #
# with a new scoring function, efficient optimization and       #
# multithreading, Journal of Computational Chemistry 31 (2010)  #
# 455-461                                                       #
#                                                               #
# DOI 10.1002/jcc.21334                                         #
#                                                               #
#################################################################

Using single ligand docking mode

Reading input ... 
Parse error on line 43 in file "/tmp/tmp6sun2q7j/0ofm24e9a.pdbqt": ATOM syntax incorrect: "CG0" is not a valid AutoDock type. Note that AutoDock atom types are case-sensitive.
done.
No valid ligands in the input directory
```

This error does not show up when running the same configuration with AutoDock Vina v.1.2.5.
So I am wondering if this new version of Vina-GPU-2.1 supports it? If not, is there any other solution to make it work?
Also, can you tell me which version of AutoDock Vina is supported?
Best Regards,

**Comment by vincrichard** [comment]
I looked more into it and Vina GPU seems to be built on top of an older version of AutoDock Vina, at least before 1.2.0 and so won't work in this case.

Are there any plans to upgrade to a newer version of AutoDock Vina? Is it even feasible with the current code base?

**Comment by Glinttsd** [comment]
Hi, thanks for following. The Vina-GPU series are based on the original older version of AutoDock Vina. Some of the features may not be supported. Unfortunately, we are not planning to provide these supports. I think the current code base is feasible to do so.

**Comment by vincrichard** [comment]
Thank you for your response.
