### ISSUE TITLE
No results found for my ligand

### ISSUE THREAD

**Issue by heqing-chriscao** [DeltaGroupNJUPT/Vina-GPU-2.1#45]
Hello,

I successfully compiled Vina-GPU 2.1 on my Linux server and ran the docking for the test case receptor and ligand, but when I ran it for my interested receptor (2b6g_Protein_Model_1H.pdbqt) with my interested ligand (2b6g_aptamer_Model_1H.pdbqt) and the testing ligand (drugbank1.pdbqt), Vina-GPU said there were no results found for my ligand but showing result for the test case ligand (drugbank1.pdbqt). 

The relevant files are attached here: 
[2b6g_Protein_Model_1H.pdbqt.txt](https://github.com/user-attachments/files/17036935/2b6g_Protein_Model_1H.pdbqt.txt)
[drugbank1.pdbqt.txt](https://github.com/user-attachments/files/17036936/drugbank1.pdbqt.txt)
[2b6g_aptamer_Model_1H.pdbqt.txt](https://github.com/user-attachments/files/17036937/2b6g_aptamer_Model_1H.pdbqt.txt)
[2b6g_config.txt](https://github.com/user-attachments/files/17036938/2b6g_config.txt)

The command lines are below. The first result is the docking of my receptor and the test case ligand, and the second void result is for my receptor and my ligand.

Here is my ascii tree structure:

AutoDock-Vina-GPU-2.1/
├─ chris_test/
│  ├─ 2b6g_aptamer_Model_1H.pdbqt
│  ├─ drugbank1.pdbqt
├─ input_file_example/
│  ├─ 2b6g_config.txt
│  ├─ 2b6g_Protein_Model_1H.pdbqt
├─ AutoDock-Vina-GPU-2.1

```
caomq@cscigpu06:~/Vina-GPU-2.1/Vina-GPU-2.1-main/AutoDock-Vina-GPU-2.1$ ./AutoDock-Vina-GPU-2-1 --config ./input_file_example/2b6g_config.txt
#################################################################
# If you used AutoDockVina-GPU 2.1 in your work, please cite:   #
#                                                               #
# Ding, Ji, et al. Vina-GPU 2.0: Further Accelerating AutoDock  #
# Vina and Its Derivatives with Graphics Processing Units.      #
# Journal of Chemical Information and Modeling (2023).          #
#                                                               #
# DOI https://doi.org/10.1021/acs.jcim.2c01504                  #
#                                                               #
# Shidi, Tang, Chen Ruiqi, Lin Mengru, Lin Qingde,              #
# Zhu Yanxiang, Wu Jiansheng, Hu Haifeng, and Ling Ming.        #
# Accelerating AutoDock Vina with GPUs.                         #
# Molecules 27.9 (2022): 3041.                                  #
#                                                               #
# DOI https://doi.org/10.3390/molecules27093041                 #
#                                                               #
# And also the origin AutoDock Vina paper:                      #
# O. Trott, A. J. Olson,                                        #
# AutoDock Vina: improving the speed and accuracy of docking    #
# with a new scoring function, efficient optimization and       #
# multithreading, Journal of Computational Chemistry 31 (2010)  #
# 455-461                                                       #
#                                                               #
# DOI 10.1002/jcc.21334                                         #
#                                                               #
#################################################################

Using virtual sreening mode

Output will be in the directory ./chris_test_out
Reading input ... done.
Setting up the scoring function ... done.
Using heuristic search_depth
Analyzing the binding site ... done.
GPU Platform: NVIDIA CUDA
GPU Device: NVIDIA GeForce RTX 2080 Ti
GPU Device: NVIDIA GeForce RTX 2080 Ti
GPU Device: NVIDIA GeForce RTX 2080 Ti
GPU Device: NVIDIA GeForce RTX 2080 Ti
Using random seed: -526956092
Perform docking|================done=================|

Refining ligand ./chris_test_out/drugbank1 results...done.
mode |   affinity | dist from best mode
     | (kcal/mol) | rmsd l.b.| rmsd u.b.
-----+------------+----------+----------
   1         -4.6      0.000      0.000
   2         -4.5     16.228     17.023
   3         -4.4     16.758     17.294
   4         -4.4     19.276     21.078
   5         -4.4     16.255     17.157
   6         -4.3      7.696     10.350
   7         -4.3      0.807      1.017
   8         -4.3      0.532      1.210
   9         -4.3     16.331     17.156
Writing ligand ./chris_test_out/drugbank1 output...done.

Refining ligand ./chris_test_out/2b6g_aptamer_Model_1H results...
No results found for ligand ./chris_test_out/2b6g_aptamer_Model_1H

AutoDockVina-GPU3 total runtime = 1.556 s
```

**Comment by Glinttsd** [comment]
Hi, I've checked your ligand. The program skips your ligand due to some error. The error is rised because your ligand is too large with more than 300 atoms, which would cause OOM for our V100 GPU with 32 GB ram. The maximum number of atoms for our V100 GPU is 130. I suggest you to use smaller ligands or the original CPU version AutoDock-Vina.

We've updated our code to print more error messages to help users find out what exact error they are facing. Hope it could be helpful.

**Comment by Glinttsd** [comment]
> Thank you for your reply and update! I could see the error message now.
> 
> Would Vina-GPU support using multiple GPUs and the NVlink to maximize the amount of effective memory that I have？

Hi, currently we have no plan to do this.

**Comment by heqing-chriscao** [comment]
> > Thank you for your reply and update! I could see the error message now.
> > Would Vina-GPU support using multiple GPUs and the NVlink to maximize the amount of effective memory that I have？
> 
> Hi, currently we have no plan to do this.

I see. Thanks for your help!
