### ISSUE TITLE
Question with segmentation fault

### ISSUE THREAD

**Issue by 1339283605** [DeltaGroupNJUPT/Vina-GPU-2.1#5]
Hello,

Thanks for this very nice tools, when I run Vina-GPU-2.1 using the test file on Linux, I had an error about segmentation fault.
Then I run this program with root permission, but it still reports this error.
![微信图片_20231113152750](https://github.com/DeltaGroupNJUPT/Vina-GPU-2.1/assets/92389627/97d4254d-a64e-4aa6-a499-55a7e3ad6dc4)
Then I used GDB to check the core file and found this error(./libio/fseek.c: the file or directory does not exist). Do you have any suggestions to solve this problem?
![13de4a58e45eb36d8e563cfa6b9f795](https://github.com/DeltaGroupNJUPT/Vina-GPU-2.1/assets/92389627/7e018357-616e-44be-a69d-6a902adf0928)
Thanks for your reply!

**Comment by yanbosmu** [comment]
I have a similar problem, how do you solve it?

**Comment by 1339283605** [comment]
Hi, for me, it's due to an error in the path in the config file, you can check the "opencl_binary_path" in the config.txt. If it's not this problem, I'm sorry that I'm not sure how to solve it.

> I have a similar problem, how do you solve it?

**Comment by yanbosmu** [comment]
> Hi, for me, it's due to an error in the path in the config file, you can check the "opencl_binary_path" in the config.txt. If it's not this problem, I'm sorry that I'm not sure how to solve it.
> 
> > I have a similar problem, how do you solve it?

YES!!!!!!
I solved it, THANK YOU VERY MUCH!
