### ISSUE TITLE
Segemantaion Fault (core dumped) 

### ISSUE THREAD

**Issue by vaghasiyautsav** [DeltaGroupNJUPT/Vina-GPU-2.1#7]
```
vaxine@VaxineGPU3:~/BioInfoSoft/Vina-GPU-2.1-main/AutoDock-Vina-GPU-2.1$ ./AutoDock-Vina-GPU-2-1 --config ./input_file_example/2bm2_config.txt
#################################################################
# If you used AutoDockVina-GPU 2.1 in your work, please cite:   #
#                                                               #
# Ding, Ji, et al. Vina-GPU 2.0: Further Accelerating AutoDock  #
# Vina and Its Derivatives with Graphics Processing Units.      #
# Journal of Chemical Information and Modeling (2023).          #
#                                                               #
# DOI https://doi.org/10.1021/acs.jcim.2c01504                  #
#                                                               #
# Shidi, Tang, Chen Ruiqi, Lin Mengru, Lin Qingde,              #
# Zhu Yanxiang, Wu Jiansheng, Hu Haifeng, and Ling Ming.        #
# Accelerating AutoDock Vina with GPUs.                         #
# Molecules 27.9 (2022): 3041.                                  #
#                                                               #
# DOI https://doi.org/10.3390/molecules27093041                 #
#                                                               #
# And also the origin AutoDock Vina paper:                      #
# O. Trott, A. J. Olson,                                        #
# AutoDock Vina: improving the speed and accuracy of docking    #
# with a new scoring function, efficient optimization and       #
# multithreading, Journal of Computational Chemistry 31 (2010)  #
# 455-461                                                       #
#                                                               #
# DOI 10.1002/jcc.21334                                         #
#                                                               #
#################################################################

Using virtual sreening mode

Output will be in the directory ./test_out
Reading input ... done.
Setting up the scoring function ... done.
Using heuristic search_depth
Analyzing the binding site ... done.
GPU Platform: NVIDIA CUDA
GPU Device: NVIDIA GeForce GTX 1650
Using random seed: 2071502842

Build kernel 1 from source
OpenCL version: 2.0
1 warning generated.

Build kernel 2 from source
OpenCL version: 2.0
Segmentation fault (core dumped)
```
getting this error while initial example run. Can anybody help here ?

**Comment by OH-AU** [comment]
Running into same (looking) issue but for QuickVina2-GPU-2.1 (using OpenCL 3.0) on an Nvidia Tesla P100 and H100.
cuda driver: 535.104.05
cuda: 12.2.2
gcc: 12.3

I then attempted to run AutoDock-Vina-GPU-2.1 since that's what this ticket is about and ran into the same error:

Using virtual sreening mode

Output will be in the directory ./test_out
Reading input ... done.
Setting up the scoring function ... done.
Using heuristic search_depth
Analyzing the binding site ... done.
GPU Platform: NVIDIA CUDA
GPU Device: NVIDIA H100 80GB HBM3
Using random seed: -1919286168

Build kernel 1 from source
OpenCL version: 3.0

Build kernel 2 from source
OpenCL version: 3.0
Segmentation fault (core dumped)

**Comment by Glinttsd** [comment]
Hi, many issues may lead to `Segmentation fault`. You can refer to our previous site [here ](https://github.com/DeltaGroupNJUPT/Vina-GPU/issues/12) to find any solution. You can also try to set a smaller `thread` or update your GPU driver to see if it works.

**Comment by vaghasiyautsav** [comment]
Hi Sir,

The issue was with config file as default address was yours file location.
I edited with this and it worked well.

`opencl_binary_path = /home/vaxine/BioInfoSoft/Vina-GPU-2.1-main/AutoDock-Vina-GPU-2.1`

Thank you for the help. :) 
Looking forward for great advancement on Vina-GPU.

**Comment by diffracteD** [comment]
> Hi Sir,
> 
> The issue was with config file as default address was yours file location. I edited with this and it worked well.
> 
> `opencl_binary_path = /home/vaxine/BioInfoSoft/Vina-GPU-2.1-main/AutoDock-Vina-GPU-2.1`
> 
> Thank you for the help. :) Looking forward for great advancement on Vina-GPU.

Does not quite help.
What's the content in that directory that resolved the issue ?
Please explain.
